### YamlMime:ManagedReference
items:
- uid: Trivver.ITrivverGameSettings
  commentId: T:Trivver.ITrivverGameSettings
  id: ITrivverGameSettings
  parent: Trivver
  children:
  - Trivver.ITrivverGameSettings.EnabledOnStart
  - Trivver.ITrivverGameSettings.GameScale
  - Trivver.ITrivverGameSettings.GameUID
  - Trivver.ITrivverGameSettings.GameVersion
  - Trivver.ITrivverGameSettings.InterruptLoadingOnSeen
  - Trivver.ITrivverGameSettings.SyncedAdSpots
  - Trivver.ITrivverGameSettings.UseSmartTab
  langs:
  - csharp
  - vb
  name: ITrivverGameSettings
  nameWithType: ITrivverGameSettings
  fullName: Trivver.ITrivverGameSettings
  type: Interface
  source:
    remote:
      path: src/trivver-unity-sdk/Assets/Plugins/Trivver.RuntimeSDK/Interfaces/ITrivverGameSettings.cs
      branch: develop
      repo: https://sergeykondratov@gitblit.saritasa.com/r/trivver/unity-sdk.git
    id: ITrivverGameSettings
    path: ../../trivver-unity-sdk/src/trivver-unity-sdk/Assets/Plugins/Trivver.RuntimeSDK/Interfaces/ITrivverGameSettings.cs
    startLine: 10
  assemblies:
  - Trivver.RuntimeSDK
  namespace: Trivver
  summary: "\nTrvver settings interface\n"
  example: []
  syntax:
    content: public interface ITrivverGameSettings
    content.vb: Public Interface ITrivverGameSettings
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Trivver.ITrivverGameSettings.GameUID
  commentId: P:Trivver.ITrivverGameSettings.GameUID
  id: GameUID
  parent: Trivver.ITrivverGameSettings
  langs:
  - csharp
  - vb
  name: GameUID
  nameWithType: ITrivverGameSettings.GameUID
  fullName: Trivver.ITrivverGameSettings.GameUID
  type: Property
  source:
    remote:
      path: src/trivver-unity-sdk/Assets/Plugins/Trivver.RuntimeSDK/Interfaces/ITrivverGameSettings.cs
      branch: develop
      repo: https://sergeykondratov@gitblit.saritasa.com/r/trivver/unity-sdk.git
    id: GameUID
    path: ../../trivver-unity-sdk/src/trivver-unity-sdk/Assets/Plugins/Trivver.RuntimeSDK/Interfaces/ITrivverGameSettings.cs
    startLine: 15
  assemblies:
  - Trivver.RuntimeSDK
  namespace: Trivver
  summary: "\nId of current game\n"
  example: []
  syntax:
    content: string GameUID { get; }
    content.vb: ReadOnly Property GameUID As String
    parameters: []
    return:
      type: System.String
  overload: Trivver.ITrivverGameSettings.GameUID*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Trivver.ITrivverGameSettings.GameScale
  commentId: P:Trivver.ITrivverGameSettings.GameScale
  id: GameScale
  parent: Trivver.ITrivverGameSettings
  langs:
  - csharp
  - vb
  name: GameScale
  nameWithType: ITrivverGameSettings.GameScale
  fullName: Trivver.ITrivverGameSettings.GameScale
  type: Property
  source:
    remote:
      path: src/trivver-unity-sdk/Assets/Plugins/Trivver.RuntimeSDK/Interfaces/ITrivverGameSettings.cs
      branch: develop
      repo: https://sergeykondratov@gitblit.saritasa.com/r/trivver/unity-sdk.git
    id: GameScale
    path: ../../trivver-unity-sdk/src/trivver-unity-sdk/Assets/Plugins/Trivver.RuntimeSDK/Interfaces/ITrivverGameSettings.cs
    startLine: 20
  assemblies:
  - Trivver.RuntimeSDK
  namespace: Trivver
  summary: "\nCoefficient of game scale\n"
  example: []
  syntax:
    content: float GameScale { get; }
    content.vb: ReadOnly Property GameScale As Single
    parameters: []
    return:
      type: System.Single
  overload: Trivver.ITrivverGameSettings.GameScale*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Trivver.ITrivverGameSettings.GameVersion
  commentId: P:Trivver.ITrivverGameSettings.GameVersion
  id: GameVersion
  parent: Trivver.ITrivverGameSettings
  langs:
  - csharp
  - vb
  name: GameVersion
  nameWithType: ITrivverGameSettings.GameVersion
  fullName: Trivver.ITrivverGameSettings.GameVersion
  type: Property
  source:
    remote:
      path: src/trivver-unity-sdk/Assets/Plugins/Trivver.RuntimeSDK/Interfaces/ITrivverGameSettings.cs
      branch: develop
      repo: https://sergeykondratov@gitblit.saritasa.com/r/trivver/unity-sdk.git
    id: GameVersion
    path: ../../trivver-unity-sdk/src/trivver-unity-sdk/Assets/Plugins/Trivver.RuntimeSDK/Interfaces/ITrivverGameSettings.cs
    startLine: 25
  assemblies:
  - Trivver.RuntimeSDK
  namespace: Trivver
  summary: "\nVersion of game\n"
  example: []
  syntax:
    content: string GameVersion { get; }
    content.vb: ReadOnly Property GameVersion As String
    parameters: []
    return:
      type: System.String
  overload: Trivver.ITrivverGameSettings.GameVersion*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Trivver.ITrivverGameSettings.UseSmartTab
  commentId: P:Trivver.ITrivverGameSettings.UseSmartTab
  id: UseSmartTab
  parent: Trivver.ITrivverGameSettings
  langs:
  - csharp
  - vb
  name: UseSmartTab
  nameWithType: ITrivverGameSettings.UseSmartTab
  fullName: Trivver.ITrivverGameSettings.UseSmartTab
  type: Property
  source:
    remote:
      path: src/trivver-unity-sdk/Assets/Plugins/Trivver.RuntimeSDK/Interfaces/ITrivverGameSettings.cs
      branch: develop
      repo: https://sergeykondratov@gitblit.saritasa.com/r/trivver/unity-sdk.git
    id: UseSmartTab
    path: ../../trivver-unity-sdk/src/trivver-unity-sdk/Assets/Plugins/Trivver.RuntimeSDK/Interfaces/ITrivverGameSettings.cs
    startLine: 30
  assemblies:
  - Trivver.RuntimeSDK
  namespace: Trivver
  summary: "\nUse SmartTab or not. If disabled, SmartTab will not be available in the system.\n"
  example: []
  syntax:
    content: bool UseSmartTab { get; }
    content.vb: ReadOnly Property UseSmartTab As Boolean
    parameters: []
    return:
      type: System.Boolean
  overload: Trivver.ITrivverGameSettings.UseSmartTab*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Trivver.ITrivverGameSettings.EnabledOnStart
  commentId: P:Trivver.ITrivverGameSettings.EnabledOnStart
  id: EnabledOnStart
  parent: Trivver.ITrivverGameSettings
  langs:
  - csharp
  - vb
  name: EnabledOnStart
  nameWithType: ITrivverGameSettings.EnabledOnStart
  fullName: Trivver.ITrivverGameSettings.EnabledOnStart
  type: Property
  source:
    remote:
      path: src/trivver-unity-sdk/Assets/Plugins/Trivver.RuntimeSDK/Interfaces/ITrivverGameSettings.cs
      branch: develop
      repo: https://sergeykondratov@gitblit.saritasa.com/r/trivver/unity-sdk.git
    id: EnabledOnStart
    path: ../../trivver-unity-sdk/src/trivver-unity-sdk/Assets/Plugins/Trivver.RuntimeSDK/Interfaces/ITrivverGameSettings.cs
    startLine: 35
  assemblies:
  - Trivver.RuntimeSDK
  namespace: Trivver
  summary: "\nDefines if SmartTab button is shown after initialization.\n"
  example: []
  syntax:
    content: bool EnabledOnStart { get; }
    content.vb: ReadOnly Property EnabledOnStart As Boolean
    parameters: []
    return:
      type: System.Boolean
  overload: Trivver.ITrivverGameSettings.EnabledOnStart*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Trivver.ITrivverGameSettings.InterruptLoadingOnSeen
  commentId: P:Trivver.ITrivverGameSettings.InterruptLoadingOnSeen
  id: InterruptLoadingOnSeen
  parent: Trivver.ITrivverGameSettings
  langs:
  - csharp
  - vb
  name: InterruptLoadingOnSeen
  nameWithType: ITrivverGameSettings.InterruptLoadingOnSeen
  fullName: Trivver.ITrivverGameSettings.InterruptLoadingOnSeen
  type: Property
  source:
    remote:
      path: src/trivver-unity-sdk/Assets/Plugins/Trivver.RuntimeSDK/Interfaces/ITrivverGameSettings.cs
      branch: develop
      repo: https://sergeykondratov@gitblit.saritasa.com/r/trivver/unity-sdk.git
    id: InterruptLoadingOnSeen
    path: ../../trivver-unity-sdk/src/trivver-unity-sdk/Assets/Plugins/Trivver.RuntimeSDK/Interfaces/ITrivverGameSettings.cs
    startLine: 40
  assemblies:
  - Trivver.RuntimeSDK
  namespace: Trivver
  summary: "\nIf true, AdSpot stops loading of asset, if it has been seen by main Camera.\n"
  example: []
  syntax:
    content: bool InterruptLoadingOnSeen { get; }
    content.vb: ReadOnly Property InterruptLoadingOnSeen As Boolean
    parameters: []
    return:
      type: System.Boolean
  overload: Trivver.ITrivverGameSettings.InterruptLoadingOnSeen*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Trivver.ITrivverGameSettings.SyncedAdSpots
  commentId: P:Trivver.ITrivverGameSettings.SyncedAdSpots
  id: SyncedAdSpots
  parent: Trivver.ITrivverGameSettings
  langs:
  - csharp
  - vb
  name: SyncedAdSpots
  nameWithType: ITrivverGameSettings.SyncedAdSpots
  fullName: Trivver.ITrivverGameSettings.SyncedAdSpots
  type: Property
  source:
    remote:
      path: src/trivver-unity-sdk/Assets/Plugins/Trivver.RuntimeSDK/Interfaces/ITrivverGameSettings.cs
      branch: develop
      repo: https://sergeykondratov@gitblit.saritasa.com/r/trivver/unity-sdk.git
    id: SyncedAdSpots
    path: ../../trivver-unity-sdk/src/trivver-unity-sdk/Assets/Plugins/Trivver.RuntimeSDK/Interfaces/ITrivverGameSettings.cs
    startLine: 45
  assemblies:
  - Trivver.RuntimeSDK
  namespace: Trivver
  summary: "\nList of AdSpots synced last time\n"
  example: []
  syntax:
    content: IEnumerable<SyncedAdSpotInfo> SyncedAdSpots { get; }
    content.vb: ReadOnly Property SyncedAdSpots As IEnumerable(Of SyncedAdSpotInfo)
    parameters: []
    return:
      type: System.Collections.Generic.IEnumerable{Trivver.SyncedAdSpotInfo}
  overload: Trivver.ITrivverGameSettings.SyncedAdSpots*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Trivver
  commentId: N:Trivver
  isExternal: false
  name: Trivver
  nameWithType: Trivver
  fullName: Trivver
- uid: Trivver.ITrivverGameSettings.GameUID*
  commentId: Overload:Trivver.ITrivverGameSettings.GameUID
  isExternal: false
  name: GameUID
  nameWithType: ITrivverGameSettings.GameUID
  fullName: Trivver.ITrivverGameSettings.GameUID
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Trivver.ITrivverGameSettings.GameScale*
  commentId: Overload:Trivver.ITrivverGameSettings.GameScale
  isExternal: false
  name: GameScale
  nameWithType: ITrivverGameSettings.GameScale
  fullName: Trivver.ITrivverGameSettings.GameScale
- uid: System.Single
  commentId: T:System.Single
  parent: System
  isExternal: true
  name: Single
  nameWithType: Single
  fullName: System.Single
- uid: Trivver.ITrivverGameSettings.GameVersion*
  commentId: Overload:Trivver.ITrivverGameSettings.GameVersion
  isExternal: false
  name: GameVersion
  nameWithType: ITrivverGameSettings.GameVersion
  fullName: Trivver.ITrivverGameSettings.GameVersion
- uid: Trivver.ITrivverGameSettings.UseSmartTab*
  commentId: Overload:Trivver.ITrivverGameSettings.UseSmartTab
  isExternal: false
  name: UseSmartTab
  nameWithType: ITrivverGameSettings.UseSmartTab
  fullName: Trivver.ITrivverGameSettings.UseSmartTab
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Trivver.ITrivverGameSettings.EnabledOnStart*
  commentId: Overload:Trivver.ITrivverGameSettings.EnabledOnStart
  isExternal: false
  name: EnabledOnStart
  nameWithType: ITrivverGameSettings.EnabledOnStart
  fullName: Trivver.ITrivverGameSettings.EnabledOnStart
- uid: Trivver.ITrivverGameSettings.InterruptLoadingOnSeen*
  commentId: Overload:Trivver.ITrivverGameSettings.InterruptLoadingOnSeen
  isExternal: false
  name: InterruptLoadingOnSeen
  nameWithType: ITrivverGameSettings.InterruptLoadingOnSeen
  fullName: Trivver.ITrivverGameSettings.InterruptLoadingOnSeen
- uid: Trivver.ITrivverGameSettings.SyncedAdSpots*
  commentId: Overload:Trivver.ITrivverGameSettings.SyncedAdSpots
  isExternal: false
  name: SyncedAdSpots
  nameWithType: ITrivverGameSettings.SyncedAdSpots
  fullName: Trivver.ITrivverGameSettings.SyncedAdSpots
- uid: System.Collections.Generic.IEnumerable{Trivver.SyncedAdSpotInfo}
  commentId: T:System.Collections.Generic.IEnumerable{Trivver.SyncedAdSpotInfo}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IEnumerable`1
  name: IEnumerable<SyncedAdSpotInfo>
  nameWithType: IEnumerable<SyncedAdSpotInfo>
  fullName: System.Collections.Generic.IEnumerable<Trivver.SyncedAdSpotInfo>
  nameWithType.vb: IEnumerable(Of SyncedAdSpotInfo)
  fullname.vb: System.Collections.Generic.IEnumerable(Of Trivver.SyncedAdSpotInfo)
  name.vb: IEnumerable(Of SyncedAdSpotInfo)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Trivver.SyncedAdSpotInfo
    name: SyncedAdSpotInfo
    nameWithType: SyncedAdSpotInfo
    fullName: Trivver.SyncedAdSpotInfo
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Trivver.SyncedAdSpotInfo
    name: SyncedAdSpotInfo
    nameWithType: SyncedAdSpotInfo
    fullName: Trivver.SyncedAdSpotInfo
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: true
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  nameWithType.vb: IEnumerable(Of T)
  fullname.vb: System.Collections.Generic.IEnumerable(Of T)
  name.vb: IEnumerable(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
