### YamlMime:ManagedReference
items:
- uid: Utils.Logging.ILoggingSettings
  commentId: T:Utils.Logging.ILoggingSettings
  id: ILoggingSettings
  parent: Utils.Logging
  children:
  - Utils.Logging.ILoggingSettings.FilterLogTags
  - Utils.Logging.ILoggingSettings.FilterLogType
  - Utils.Logging.ILoggingSettings.LogEnabled
  langs:
  - csharp
  - vb
  name: ILoggingSettings
  nameWithType: ILoggingSettings
  fullName: Utils.Logging.ILoggingSettings
  type: Interface
  source:
    remote:
      path: src/Trivver.Libs/Trivver.Logging/Utils/Logging/ILoggingSettings.cs
      branch: develop
      repo: https://sergeykondratov@gitblit.saritasa.com/r/trivver/unity-sdk.git
    id: ILoggingSettings
    path: ../../trivver-unity-sdk/src/Trivver.Libs/Trivver.Logging/Utils/Logging/ILoggingSettings.cs
    startLine: 8
  assemblies:
  - Trivver.Logging
  namespace: Utils.Logging
  summary: "\nInterface for logging settings\n"
  example: []
  syntax:
    content: public interface ILoggingSettings
    content.vb: Public Interface ILoggingSettings
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Utils.Logging.ILoggingSettings.FilterLogType
  commentId: P:Utils.Logging.ILoggingSettings.FilterLogType
  id: FilterLogType
  parent: Utils.Logging.ILoggingSettings
  langs:
  - csharp
  - vb
  name: FilterLogType
  nameWithType: ILoggingSettings.FilterLogType
  fullName: Utils.Logging.ILoggingSettings.FilterLogType
  type: Property
  source:
    remote:
      path: src/Trivver.Libs/Trivver.Logging/Utils/Logging/ILoggingSettings.cs
      branch: develop
      repo: https://sergeykondratov@gitblit.saritasa.com/r/trivver/unity-sdk.git
    id: FilterLogType
    path: ../../trivver-unity-sdk/src/Trivver.Libs/Trivver.Logging/Utils/Logging/ILoggingSettings.cs
    startLine: 14
  assemblies:
  - Trivver.Logging
  namespace: Utils.Logging
  summary: "\nLog type filter\n"
  example: []
  syntax:
    content: LogType FilterLogType { get; set; }
    content.vb: Property FilterLogType As LogType
    parameters: []
    return:
      type: UnityEngine.LogType
  overload: Utils.Logging.ILoggingSettings.FilterLogType*
  modifiers.csharp:
  - get
  - set
- uid: Utils.Logging.ILoggingSettings.FilterLogTags
  commentId: P:Utils.Logging.ILoggingSettings.FilterLogTags
  id: FilterLogTags
  parent: Utils.Logging.ILoggingSettings
  langs:
  - csharp
  - vb
  name: FilterLogTags
  nameWithType: ILoggingSettings.FilterLogTags
  fullName: Utils.Logging.ILoggingSettings.FilterLogTags
  type: Property
  source:
    remote:
      path: src/Trivver.Libs/Trivver.Logging/Utils/Logging/ILoggingSettings.cs
      branch: develop
      repo: https://sergeykondratov@gitblit.saritasa.com/r/trivver/unity-sdk.git
    id: FilterLogTags
    path: ../../trivver-unity-sdk/src/Trivver.Libs/Trivver.Logging/Utils/Logging/ILoggingSettings.cs
    startLine: 19
  assemblies:
  - Trivver.Logging
  namespace: Utils.Logging
  summary: "\nCollection of tags which will not go to log\n"
  example: []
  syntax:
    content: ICollection<string> FilterLogTags { get; }
    content.vb: ReadOnly Property FilterLogTags As ICollection(Of String)
    parameters: []
    return:
      type: System.Collections.Generic.ICollection{System.String}
  overload: Utils.Logging.ILoggingSettings.FilterLogTags*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Utils.Logging.ILoggingSettings.LogEnabled
  commentId: P:Utils.Logging.ILoggingSettings.LogEnabled
  id: LogEnabled
  parent: Utils.Logging.ILoggingSettings
  langs:
  - csharp
  - vb
  name: LogEnabled
  nameWithType: ILoggingSettings.LogEnabled
  fullName: Utils.Logging.ILoggingSettings.LogEnabled
  type: Property
  source:
    remote:
      path: src/Trivver.Libs/Trivver.Logging/Utils/Logging/ILoggingSettings.cs
      branch: develop
      repo: https://sergeykondratov@gitblit.saritasa.com/r/trivver/unity-sdk.git
    id: LogEnabled
    path: ../../trivver-unity-sdk/src/Trivver.Libs/Trivver.Logging/Utils/Logging/ILoggingSettings.cs
    startLine: 24
  assemblies:
  - Trivver.Logging
  namespace: Utils.Logging
  summary: "\nAllows to disable logging\n"
  example: []
  syntax:
    content: bool LogEnabled { get; set; }
    content.vb: Property LogEnabled As Boolean
    parameters: []
    return:
      type: System.Boolean
  overload: Utils.Logging.ILoggingSettings.LogEnabled*
  modifiers.csharp:
  - get
  - set
references:
- uid: Utils.Logging
  commentId: N:Utils.Logging
  isExternal: false
  name: Utils.Logging
  nameWithType: Utils.Logging
  fullName: Utils.Logging
- uid: Utils.Logging.ILoggingSettings.FilterLogType*
  commentId: Overload:Utils.Logging.ILoggingSettings.FilterLogType
  isExternal: false
  name: FilterLogType
  nameWithType: ILoggingSettings.FilterLogType
  fullName: Utils.Logging.ILoggingSettings.FilterLogType
- uid: UnityEngine.LogType
  commentId: T:UnityEngine.LogType
  parent: UnityEngine
  isExternal: true
  name: LogType
  nameWithType: LogType
  fullName: UnityEngine.LogType
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: false
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: Utils.Logging.ILoggingSettings.FilterLogTags*
  commentId: Overload:Utils.Logging.ILoggingSettings.FilterLogTags
  isExternal: false
  name: FilterLogTags
  nameWithType: ILoggingSettings.FilterLogTags
  fullName: Utils.Logging.ILoggingSettings.FilterLogTags
- uid: System.Collections.Generic.ICollection{System.String}
  commentId: T:System.Collections.Generic.ICollection{System.String}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.ICollection`1
  name: ICollection<String>
  nameWithType: ICollection<String>
  fullName: System.Collections.Generic.ICollection<System.String>
  nameWithType.vb: ICollection(Of String)
  fullname.vb: System.Collections.Generic.ICollection(Of System.String)
  name.vb: ICollection(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.ICollection`1
    name: ICollection
    nameWithType: ICollection
    fullName: System.Collections.Generic.ICollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.ICollection`1
    name: ICollection
    nameWithType: ICollection
    fullName: System.Collections.Generic.ICollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.ICollection`1
  commentId: T:System.Collections.Generic.ICollection`1
  isExternal: true
  name: ICollection<T>
  nameWithType: ICollection<T>
  fullName: System.Collections.Generic.ICollection<T>
  nameWithType.vb: ICollection(Of T)
  fullname.vb: System.Collections.Generic.ICollection(Of T)
  name.vb: ICollection(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.ICollection`1
    name: ICollection
    nameWithType: ICollection
    fullName: System.Collections.Generic.ICollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.ICollection`1
    name: ICollection
    nameWithType: ICollection
    fullName: System.Collections.Generic.ICollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: Utils.Logging.ILoggingSettings.LogEnabled*
  commentId: Overload:Utils.Logging.ILoggingSettings.LogEnabled
  isExternal: false
  name: LogEnabled
  nameWithType: ILoggingSettings.LogEnabled
  fullName: Utils.Logging.ILoggingSettings.LogEnabled
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
